---
Q6. List the top two most reported disease illnesses in each state over the past three 
years, along with the corresponding average Air Quality Index (AQI) for that 
period. 
---

In [5]:
import pandas as pd
data=pd.read_csv('day-wise-state-wise-air-quality-index-aqi-of-major-cities-and-towns-in-india.csv')
health_data = pd.read_csv('state_wise_disease.csv', encoding_errors='replace')
health_data.drop(['unit','note'],axis=1,inplace=True)

In [9]:
health_data=health_data[health_data['year']>=2022]
illnesses=health_data.groupby(['state','disease_illness_name'])['cases'].sum().reset_index(name='Total_cases')
illnesses=pd.DataFrame(illnesses)
res=[]
for state in illnesses['state'].unique():
    df=illnesses[illnesses['state']==state].sort_values(by='Total_cases',ascending=False)
    top_2=df.head(2)
    res.append(top_2)
res=pd.concat(res)

# avg AQI by states
state_aqi_filter=data[data['date']>='2022-01-01']
state_aqi_avg=state_aqi_filter.groupby('state')['aqi_value'].mean().reset_index(name='avg_aqi')
state_aqi_avg

new=pd.merge(res[['state','disease_illness_name']],state_aqi_avg[['state','avg_aqi']],on='state')
new = new.reset_index(drop=True)
new

                          state     disease_illness_name     avg_aqi
0   Andaman and Nicobar Islands  Acute Diarrheal Disease   60.342857
1   Andaman and Nicobar Islands          Fever with Rash   60.342857
2                Andhra Pradesh  Acute Diarrheal Disease   81.963460
3                Andhra Pradesh                  Cholera   81.963460
4             Arunachal Pradesh  Acute Diarrheal Disease   58.241706
..                          ...                      ...         ...
58                Uttar Pradesh           Food Poisoning  158.519647
59                  Uttarakhand                   Dengue   85.262411
60                  Uttarakhand  Acute Diarrheal Disease   85.262411
61                  West Bengal  Acute Diarrheal Disease  117.496899
62                  West Bengal           Food Poisoning  117.496899

[63 rows x 3 columns]

In [13]:
with pd.option_context('display.max_rows', None):
    display(new)

,state,disease_illness_name,Total_cases,avg_aqi
0,Delhi,Dengue,40.0,207.392095
1,Delhi,Measles,2.0,207.392095
2,Bihar,Acute Diarrheal Disease,1367.0,160.371841
3,Bihar,Dengue,856.0,160.371841
4,Jharkhand,Malaria,5927.0,160.217335
5,Jharkhand,Acute Diarrheal Disease,1700.0,160.217335
6,Himachal Pradesh,Acute Diarrheal Disease,2273.0,160.133040
7,Himachal Pradesh,Hepatitis A,559.0,160.133040
8,Haryana,Cholera,972.0,143.163307
9,Haryana,Acute Diarrheal Disease,733.0,143.163307
10,Chandigarh,Cholera,16.0,140.816456
11,Tripura,Acute Diarrheal Disease,399.0,132.262522
12,Tripura,Dengue,259.0,132.262522
13,Uttar Pradesh,Acute Diarrheal Disease,4415.0,128.607838
14,Uttar Pradesh,Food Poisoning,2446.0,128.607838
15,Rajasthan,Acute Diarrheal Disease,1655.0,127.464524
16,Rajasthan,Dengue,836.0,127.464524
17,Odisha,Acute Diarrheal Disease,6276.0,122.095715
18,Odisha,Food Poisoning,3922.0,122.095715
19,Punjab,Acute Diarrheal Disease,1934.0,117.472538
20,Punjab,Cholera,715.0,117.472538
21,West Bengal,Acute Diarrheal Disease,4822.0,115.865575
22,West Bengal,Food Poisoning,3345.0,115.865575
23,Assam,Acute Diarrheal Disease,2803.0,113.383406
24,Assam,Food Poisoning,1784.0,113.383406
25,Gujarat,Acute Diarrheal Disease,5282.0,111.626806
26,Gujarat,Food Poisoning,4951.0,111.626806
27,Madhya Pradesh,Acute Diarrheal Disease,6936.0,109.423128
28,Madhya Pradesh,Dengue,2212.0,109.423128
29,Maharashtra,Acute Diarrheal Disease,7621.0,102.794081
30,Maharashtra,Food Poisoning,4809.0,102.794081
31,Manipur,Dengue,3072.0,101.246512
32,Manipur,Food Poisoning,147.0,101.246512
33,Uttarakhand,Dengue,1300.0,86.912760
34,Uttarakhand,Acute Diarrheal Disease,757.0,86.912760
35,Telangana,Acute Diarrheal Disease,1195.0,83.308300
36,Telangana,Food Poisoning,753.0,83.308300
37,Nagaland,Dengue,1244.0,81.168539
38,Nagaland,Acute Diarrheal Disease,148.0,81.168539
39,Andhra Pradesh,Acute Diarrheal Disease,3289.0,77.900612
40,Andhra Pradesh,Cholera,1081.0,77.900612
41,Chhattisgarh,Acute Diarrheal Disease,9035.0,77.811845
42,Chhattisgarh,Food Poisoning,768.0,77.811845
43,Jammu and Kashmir,Dengue,1474.0,77.120459
44,Jammu and Kashmir,Hepatitis A,1142.0,77.120459
45,Kerala,Food Poisoning,10584.0,68.493114
46,Kerala,Acute Diarrheal Disease,5679.0,68.493114
47,Tamil Nadu,Acute Diarrheal Disease,3116.0,66.377613
48,Tamil Nadu,Mumps,1403.0,66.377613
49,Karnataka,Acute Diarrheal Disease,8368.0,63.153353
50,Karnataka,Cholera,4452.0,63.153353
51,Meghalaya,Acute Diarrheal Disease,631.0,61.052469
52,Meghalaya,Measles,586.0,61.052469
53,Andaman and Nicobar Islands,Acute Diarrheal Disease,117.0,60.523810
54,Andaman and Nicobar Islands,Fever with Rash,8.0,60.523810
55,Arunachal Pradesh,Acute Diarrheal Disease,347.0,58.600707
56,Arunachal Pradesh,Chickenpox,166.0,58.600707
57,Puducherry,Acute Diarrheal Disease,193.0,56.481172
58,Puducherry,Dengue,72.0,56.481172
59,Sikkim,Jaundice,136.0,53.469505
60,Sikkim,Typhoid,111.0,53.469505
61,Mizoram,Food Poisoning,387.0,47.899026
62,Mizoram,Scrub Typhus,233.0,47.899026
63,Goa,Cholera,226.0,NaN
64,Ladakh,Mumps,111.0,NaN
65,Dadra and Nagar Haveli,Fever of Unknown andigin (PUO),101.0,NaN
66,Dadra and Nagar Haveli,Acute Diarrheal Disease,89.0,NaN
67,Ladakh,Hand Foot and Mouth Disease,52.0,NaN
68,Goa,Dengue,37.0,NaN
69,Madhya,Measles,36.0,NaN
70,Dadra and Nagar Haveli and Daman and Diu,Food Poisoning,24.0,NaN
71,Dadra and Nagar Haveli and Daman and Diu,Acute Diarrheal Disease,23.0,NaN
72,Tamil nadu,Mumps,14.0,NaN
73,Madhya,Chickenpox,7.0,NaN
74,Arunachal,Rabies,1.0,NaN
75,Uttar,Human Rabies,1.0,NaN

 **Conclusion:** Airborne diseases are respiratory diseases, but the data show Acute Diarrheal Disease, which has no correlation with the AQI. Hence, this data is insufficient